version: '3.3'

services:
  greeting:
    container_name: greeting
    image: greeting:latest
    build: greeting
    ports:
      - "8080:8080"

  person:
    container_name: person
    image: person:latest
    build: person
    ports:
      - "8180:8180"
    environment:
      LOG_PATH: ${HOME_PATH}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ${HOST_PATH}:${HOME_PATH}:rw

  proxy:
    container_name: proxy
    image: proxy:latest
    build: proxy
    ports:
      - "8280:80"